### ISSUE TITLE
URIs returned by GraphQL API not properly encoded

### ISSUE THREAD

**Issue by hoechenberger** [OpenNeuroOrg/openneuro#2400]
**Describe the bug**

The URIs returned by the GraphQL API are not properly encoded and may therefore not always be easily accessed programmatically.

**To Reproduce**

Execute the following GraphQL query on https://openneuro.org/crn/graphql:

```graphql
query {
  dataset(id: "ds000248") {
    latestSnapshot {
      id
      files(
        prefix: "derivatives/freesurfer/subjects/sub-01/mri/aparc+aseg.mgz"
      ) {
        urls
      }
    }
  }
}
```

The returned URI for this file is:
```
https://s3.amazonaws.com/openneuro.org/ds000248/derivatives/freesurfer/subjects/sub-01/mri/aparc+aseg.mgz?versionId=2Wx7w.fCYeGzGWLnW9sxWsPdztl.2HL0
```

However, trying to access it yields a 404 error. The culprit is the un-encoded `+` character in the filename. If one URL-encodes the `+`, producing:
```
https://s3.amazonaws.com/openneuro.org/ds000248/derivatives/freesurfer/subjects/sub-01/mri/aparc%2baseg.mgz?versionId=2Wx7w.fCYeGzGWLnW9sxWsPdztl.2HL0
```
the URI is valid.

**Expected behavior**
The returned URIs in the `urls` array should point to existing resources. Special characters need to be properly encoded.

**Additional info**
I also checked with the latest stable version of `openneuro-cli` and it, too, yields a 404 for above file.

**Comment by agramfort** [comment]
I suspect it’s because you have a + in the file name

**Comment by hoechenberger** [comment]
> I suspect it’s because you have a + in the file name

Yes, exactly. The backend needs to URL-encode the filename in the URL, which in this particular case means replacing `+` with `%2b`:

```javascript
> encodeURIComponent("aparc+aseg.mgz")
'aparc%2Baseg.mgz'
```

Note that `encodeURI` will not work here, as `+` has a special meaning in URLs:
```javascript
> encodeURI("aparc+aseg.mgz")
'aparc+aseg.mgz'
```

**Comment by hoechenberger** [comment]
Friendly bump :) Please let me know if and how I can help fixing this.

**Comment by nellh** [comment]
> Friendly bump :) Please let me know if and how I can help fixing this.

Should be fixed now with #2506 but if you have other examples of files that were not working because of this issue, I'd like to add some more examples to the test.

**Comment by hoechenberger** [comment]
Cool, thank you!

**Comment by hoechenberger** [comment]
Hello @nellh,

and happy new year! 🥳 

Has the fix from #2506 already been deployed? If yes, then apparently it didn't fully resolve the issue, sorry 😕

I just ran the abovementioned GraphQL query again, and it still produces the exact same result: returned URL is
```
https://s3.amazonaws.com/openneuro.org/ds000248/derivatives/freesurfer/subjects/sub-01/mri/aparc+aseg.mgz?versionId=2Wx7w.fCYeGzGWLnW9sxWsPdztl.2HL0
```
meaning the `+` character remains un-encoded, and the URL is inaccessible.

I would appreciate if you could once more look into this. I'm happy to help you test things!

Best wishes,
Richard

**Comment by nellh** [comment]
The fix has been deployed but these file trees are part of an immutable cache which has not yet been cleared for every dataset. I cleared it for ds000248 and the rest of the datasets should finish rebuilding this cache over the next week or so.

**Comment by hoechenberger** [comment]
Thank you!
