### ISSUE TITLE
afni_proc BIDS App interface does not list any participants in drop down

### ISSUE THREAD

**Issue by Shotgunosine** [OpenNeuroOrg/openneuro#303]
I've tested this on a few different datasets, but when selecting the afni_proc app, no participants are listed in the participants drop down. Other apps show participants in the participant dropdown, and on the dev server the participants are listed correctly. As far as I can tell, no issues are being thrown in the console and there aren't any network errors. Is there some change I need to make to get participants listed correctly?

Prod example that fails to list participants: 
https://openneuro.org/datasets/ds001110/versions/00003
Dev example with participants listed correctly:
 https://openneuro.dev.sqm.io/datasets/ds000123/versions/00001

**Comment by nellh** [comment]
V3 should work now.

**Comment by Shotgunosine** [comment]
As far as I can tell, V3 is still failing to list participants:
https://openneuro.org/datasets/ds000009/versions/00002

**Comment by nellh** [comment]
@Shotgunosine Sorry about that, looks like Chris didn't save it. V4 is fixed.

**Comment by chrisgorgo** [comment]
Definitively not my day! Thanks Nell!

Best,
Chris

**Comment by Shotgunosine** [comment]
Yep, looks good, Thanks!
