### ISSUE TITLE
ezBIDS transfer failing

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3095]
### What went wrong?

A user's ezBIDS transfer is failing. The zip file is being filled with the UTF-8 response "Bad Request".

<img width="1811" alt="Screenshot 2024-07-09 at 11 52 31 AM" src="https://github.com/OpenNeuroOrg/openneuro/assets/83442/e1a97f4f-d367-4afa-9eae-2f4b17fe82d8">

```console
user@worker-0:/datasets/uploads/ds005308/66/8d/668d52f7bb0fde9779952d44# cat 668d52f7bb0fde9779952d44.zip
Bad Request
```

This seems likely to be a problem on the ezBIDS endpoint, but we may want to handle this failure mode differently.

cc @dlevitas

### Expected behavior

ezBIDS success

**Comment by dlevitas** [comment]
Thanks for the ping, @effigies 

I've pushed a commit ([4e9e884](https://github.com/brainlife/ezbids/commit/4e9e88434239631fa04e9ff9cb546636679a835b)) that should fix this issue, thanks @nicoalee for the assist. The user will need to clear their browser cache and restart ezBIDS for the change to take effect.

**Comment by effigies** [comment]
I've notified the user to retry. If they're still having issues, I'll reopen.

**Comment by effigies** [comment]
Now the zip file contains "Unauthorized".

**Comment by dlevitas** [comment]
Okay, I increased our JSON Web Token (JWT) expiration time from 10s to 600s (10min) in this commit ([42a8abd](https://github.com/brainlife/ezbids/commit/42a8abd9faf19bdb2622089ae2b189950ecd81fb)). Tested a few uploads and things seem to work properly. 

I don't frequently transfer ezBIDS data to OpenNeuro, so do you happen to know the average wait time for data uploads to OpenNeuro. I'll need to increase the expiration time if 10 minutes isn't enough.

**Comment by effigies** [comment]
I don't know, but I'll ask the user to try again.

**Comment by dlevitas** [comment]
Feel free to give the user my email (dlevitas@iu.edu), may be more efficient.

**Comment by effigies** [comment]
Seems to have worked this time.
