### ISSUE TITLE
Access denied to many datasets on GraphQL and web interface

### ISSUE THREAD

**Issue by larsoner** [OpenNeuroOrg/openneuro#3699]
1. Navigate to https://openneuro.org/datasets/ds003775/versions/1.2.1
2. Click the "download" button on the README file
3. Get error XML:

```
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2025-12-18T16:41:08Z</Expires>
<ServerTime>2025-12-20T03:19:18Z</ServerTime>
<RequestId>BHS3SG8NSDHP9MAG</RequestId>
<HostId>B+5QFoWqWdfUH7/XQIsW3I3Vqz3NpEP1/ZuaSMIvDd957eIOZdkU0YXm81dEyKpvhALPZsyO544=</HostId>
</Error>
```

Originally observed with openneuro-py in [this CircleCI run](https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/5269/workflows/012b1f82-4cea-4b9a-8412-f810a7e0bfb8/jobs/89611) on 2025/12/19 around 3 eastern time, same error still happening on web interface and using GraphQL-based openneuropy as of 10 PM eastern time.

Not unique to ds003775, see failures with about half the datasets (3775, 1971, 1810, 247, 246, 117) here

https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/5269/workflows/012b1f82-4cea-4b9a-8412-f810a7e0bfb8

**Comment by larsoner** [comment]
... probably a dup of #3698

**Comment by effigies** [comment]
I think this should have been fixed in #3693, but maybe the redis cache needs to be dropped to expire the entries that predated the timeout?

**Comment by larsoner** [comment]
Don't know... but still appears to be a problem [as of yesterday](https://github.com/mne-tools/mne-bids-pipeline/pull/1149)

**Comment by effigies** [comment]
Yes, this probably won't be fixed this week.

**Comment by nellh** [comment]
I just manually dropped this cache to temporarily fix this.

**Comment by effigies** [comment]
I suspect this is generally fixed, and it was a one-time cache drop needed. Will let you close if you agree, @nellh.

**Comment by larsoner** [comment]
Yes this has been fixed! #3695 is [still a problem](https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/5275/workflows/5f3b1da9-e03c-4666-a2ef-b741e947061a/jobs/90057), though, FWIW

**Comment by nellh** [comment]
This should be resolved, I verified that the related cache entries have the correct timeout set.
