### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0 (openneuro-cli)

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#630]
```
$ yarn openneuro upload -i /d/data/ds000051_small/
yarn run v1.6.0
$ node packages/openneuro-cli/src upload -i D:/data/ds000051_small
? This will create a new dataset, continue? Yes
"ds001187" created with label "ds000051_small"
Transferring "D:\data\ds000051_small\CHANGES" - 100% complete
Transferring "D:\data\ds000051_small\dataset_description.json" - 100% complete
Transferring "D:\data\ds000051_small\README" - 100% complete
Transferring "D:\data\ds000051_small\task-abstractconcretejudgment_bold.json" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_inplaneT2.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_T1w.nii.gz" - 40% complete (2.7 MB remaining)
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_T1w.nii.gz" - 98% complete (106.6 KB remaining)
{ Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:121:28)
    at Object.error (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:991:28)
    at notifySubscription (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:130:18)
    at onNotify (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:161:3)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:220:7)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\zen-observable\zen-observable.js:178:20)
    at linkFetch.then.then.then.catch.error (D:\drive\workspace\openneuro\node_modules\apollo-upload-client\src\index.js:143:24)
    at process._tickCallback (internal/process/next_tick.js:178:7)
  graphQLErrors: [],
  networkError:
   { SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at D:\drive\workspace\openneuro\node_modules\apollo-link-http-common\lib\bundle.umd.js:43:25
    at process._tickCallback (internal/process/next_tick.js:178:7)
     response:
      Response {
        size: 0,
        timeout: 0,
        [Symbol(Body internals)]: [Object],
        [Symbol(Response internals)]: [Object] },
     statusCode: 504,
     bodyText: '<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.13.12</center>\r\n</body>\r\n</html>\r\n' },
  message: 'Network error: Unexpected token < in JSON at position 0',
  extraInfo: undefined }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chrisgorgo** [comment]
Second try lead to upload failure at a different file:
```
$ yarn openneuro upload -i /d/data/ds000051_small/
yarn run v1.6.0
$ node packages/openneuro-cli/src upload -i D:/data/ds000051_small
? This will create a new dataset, continue? Yes
"ds001188" created with label "ds000051_small"
Transferring "D:\data\ds000051_small\CHANGES" - 100% complete
Transferring "D:\data\ds000051_small\dataset_description.json" - 100% complete
Transferring "D:\data\ds000051_small\README" - 100% complete
Transferring "D:\data\ds000051_small\task-abstractconcretejudgment_bold.json" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_inplaneT2.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_T1w.nii.gz" - 40% complete (2.7 MB remaining)
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_T1w.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-02_T1w.nii.gz" - 43% complete (2.5 MB remaining)
{ Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:121:28)
    at Object.error (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:991:28)
    at notifySubscription (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:130:18)
    at onNotify (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:161:3)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:220:7)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\zen-observable\zen-observable.js:178:20)
    at linkFetch.then.then.then.catch.error (D:\drive\workspace\openneuro\node_modules\apollo-upload-client\src\index.js:143:24)
    at process._tickCallback (internal/process/next_tick.js:178:7)
  graphQLErrors: [],
  networkError:
   { SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at D:\drive\workspace\openneuro\node_modules\apollo-link-http-common\lib\bundle.umd.js:43:25
    at process._tickCallback (internal/process/next_tick.js:178:7)
     response:
      Response {
        size: 0,
        timeout: 0,
        [Symbol(Body internals)]: [Object],
        [Symbol(Response internals)]: [Object] },
     statusCode: 504,
     bodyText: '<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.13.12</center>\r\n</body>\r\n</html>\r\n' },
  message: 'Network error: Unexpected token < in JSON at position 0',
  extraInfo: undefined }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nellh** [comment]
This should be fixed in #622, which was just merged. Can you update and try with that?

**Comment by chrisgorgo** [comment]
Still getting the error. The CLI is at c6f19148ab1d2cc86f63346cce155b7c36d9247d (current master), but I am uploading to https://openneuro.dev.sqm.io. Could that be the issue? How can I test the CLI against localhost?

**Comment by nellh** [comment]
To test on localhost, you can edit the .openneuro configuration file (~/.openeuro - location depends on platform) to use the http://localhost:9876 URL instead. You have to make a key on localhost and add that to the same config file.

I just resynced dev, it may have been on the wrong commit. I was able to upload a few datasets with c6f1914 and dev as it is now.

**Comment by chrisgorgo** [comment]
Still failing on dev.sqm.io. localhost fails with
```
$ node packages/openneuro-cli/src upload -i D:/data/ds000051_small
? This will create a new dataset, continue? Yes
(node:25000) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:121:28)
    at Object.error (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:991:28)
    at notifySubscription (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:130:18)
    at onNotify (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:161:3)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:220:7)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\zen-observable\zen-observable.js:178:20)
    at linkFetch.then.then.then.catch.error (D:\drive\workspace\openneuro\node_modules\apollo-upload-client\src\index.js:143:24)
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:25000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:25000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 3.67s.
```
However, I don't have the datalad backend enabled and properly configured on localhost.

**Comment by olgn** [comment]
@jstiehl  and I ran into that problem yesterday while testing some things - logging in (with openneuro.dev generated api key), and ensuring that the docker containers (both app and datalad-service) were up to date removed the error.

**Comment by chrisgorgo** [comment]
If there is a new version ond dev I can try again.

Best,
Chris

**Comment by chrisgorgo** [comment]
Tried with current master agains dev.sqm.io. Still failing with slightly different error:
```
filo@MSI MINGW64 /d/drive/workspace/openneuro (master)
$ yarn openneuro upload -i /d/data/ds000051_small/
yarn run v1.6.0
$ node packages/openneuro-cli/src upload -i D:/data/ds000051_small
? This will create a new dataset, continue? Yes
"ds001199" created with label "ds000051_small"
Transferring "D:\data\ds000051_small\CHANGES" - 100% complete
Transferring "D:\data\ds000051_small\dataset_description.json" - 100% complete
Transferring "D:\data\ds000051_small\README" - 100% complete
Transferring "D:\data\ds000051_small\task-abstractconcretejudgment_bold.json" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_inplaneT2.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_T1w.nii.gz" - 40% complete (2.7 MB remaining)
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_T1w.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-02_T1w.nii.gz" - 55% complete (2.0 MB remaining)
(node:19700) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:121:28)
    at Object.error (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:991:28)
    at notifySubscription (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:130:18)
    at onNotify (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:161:3)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:220:7)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\zen-observable\zen-observable.js:178:20)
    at D:\drive\workspace\openneuro\node_modules\apollo-upload-client\lib\main\index.js:156:24
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:19700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 101.39s.
```

**Comment by chrisgorgo** [comment]
When trying against local:
```
$ node packages/openneuro-cli/src upload -i D:/data/ds000051_small
? This will create a new dataset, continue? Yes
(node:26728) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:121:28)
    at Object.error (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:991:28)
    at notifySubscription (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:130:18)
    at onNotify (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:161:3)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:220:7)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\zen-observable\zen-observable.js:178:20)
    at D:\drive\workspace\openneuro\node_modules\apollo-upload-client\lib\main\index.js:156:24
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:26728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:26728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chrisgorgo** [comment]
I never got the CLI to work. Was there a new fix deployed?

**Comment by chrisgorgo** [comment]
I just tried it on local master. Previous error was caused by lack of backslash in `~/.openneuro`. After adding this I wa able to inch forward, but run into another error:

```
$ node packages/openneuro-cli/src upload -i D:/data/ds000051_small
? This will create a new dataset, continue? Yes
"ds001001" created with label "ds000051_small"
Transferring "D:\data\ds000051_small\CHANGES" - 100% complete
Transferring "D:\data\ds000051_small\dataset_description.json" - 100% complete
Transferring "D:\data\ds000051_small\README" - 100% complete
Transferring "D:\data\ds000051_small\task-abstractconcretejudgment_bold.json" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_inplaneT2.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_T1w.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-02_T1w.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\func\sub-01_task-abstractconcretejudgment_run-01_bold.nii.gz" - 30% complete (13.5 MB remaining)
(node:8372) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:121:28)
    at Object.error (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:991:28)
    at notifySubscription (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:130:18)
    at onNotify (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:161:3)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:220:7)
    at SubscriptionObserver.error (D:\drive\workspace\openneuro\node_modules\zen-observable\zen-observable.js:178:20)
    at D:\drive\workspace\openneuro\node_modules\apollo-upload-client\lib\main\index.js:156:24
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:8372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 70.38s.
```

Server logs seem to show this is a timeout issue
```
nginx_1    | 2018/05/15 01:59:59 [error] 7#7: *159 upstream timed out (110: Connection timed out) while sending request to upstream, client: 172.18.0.1, server: , request: "POST /crn/graphql HTTP/1.1", upstream: "http://172.18.0.9:8111/crn/graphql", host: "localhost:9876"
nginx_1    | 172.18.0.1 - - [15/May/2018:01:59:59 +0000] "POST /crn/graphql HTTP/1.1" 504 184 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" "-"
```

**Comment by nellh** [comment]
@chrisfilo What version of the datalad-service are you running and can you provide those logs? `docker-compose logs datalad`

**Comment by chrisgorgo** [comment]
Version a46bce68dabad04088da59162af863682f560428 (seems to be current master)

logs
```
[2018-05-15 01:50:49 +0000] [1] [INFO] Starting gunicorn 19.7.1
[2018-05-15 01:50:49 +0000] [1] [INFO] Listening at: http://0.0.0.0:9877 (1)
[2018-05-15 01:50:49 +0000] [1] [INFO] Using worker: sync
[2018-05-15 01:50:49 +0000] [10] [INFO] Booting worker with pid: 10

[WARNING] It is highly recommended to configure git first (set both user.name and user.email) before using DataLad. Failed to verify that git is configured: CommandError: command '['git', 'config', 'user.name']' failed with exitcode 1
| Failed to run ['git', 'config', 'user.name'] under None. Exit code=1. out= err= [cmd.py:run:520]CommandError: command '['git', 'config', 'user.email']' failed with exitcode 1
| Failed to run ['git', 'config', 'user.email'] under None. Exit code=1. out= err= [cmd.py:run:520].  Some operations might fail or not perform correctly. 
[INFO] Creating a new annex repo at /datalad/ds001001 
```
Seems to be a git config issue. This config init has to be done within the container?

**Comment by nellh** [comment]
That warning won't affect uploads and the fix for that is tracked in https://github.com/OpenNeuroOrg/datalad-service/issues/7 - to summarize the behavior that's been implemented since, if we can easily link the action to a user the commit author includes the user's OpenNeuro email and name. If not, `OpenNeuro Git Worker <git@openneuro.org>` is used.

I'm not sure what's going on here. It looks like an HTTP request between containers is failing, we don't have a proper handler for non-JSON responses since the API returns errors as JSON, making the traceback not very helpful. Does the 1.13 npm package work against dev or do you see the same issue?

**Comment by chrisgorgo** [comment]
I've tried using npm package against dev. It did not error, but I cannot see the dataset on my dashboard

```
$ openneuro upload -i /d/data/ds000051_small/
? This will create a new dataset, continue? Yes
"ds001202" created with label "ds000051_small"
Transferring "D:\data\ds000051_small\CHANGES" - 100% complete
Transferring "D:\data\ds000051_small\dataset_description.json" - 100% complete
Transferring "D:\data\ds000051_small\README" - 100% complete
Transferring "D:\data\ds000051_small\task-abstractconcretejudgment_bold.json" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_inplaneT2.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-01_T1w.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small\sub-01\anat\sub-01_run-02_T1w.nii.gz" - 55% complete (2.0 MB remaining)

filo@MSI MINGW64 /d/drive/workspace/openneuro (master)
$ openneuro --version
1.13.0
```
The last step (uploading `sub-01_run-02_T1w.nii.gz`) took substantially longer than others.

**Comment by nellh** [comment]
This is the same issue as #646 which has info about the problem, closing this out in favor of that.
