### ISSUE TITLE
Error: The component has been loading for too long. Reverting render to component error boundary.

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#938]
This performance issue has been observed since datalad/graphql transition. The latest performance updates in 2.3.0 helped to some extent, but since the release users are still running into this issue as indicated by the sentry logs.

https://sentry.io/openneuro/openneuro/issues/634329332/

```
Error: The component has been loading for too long. Reverting render to component error boundary.
  at render (./scripts/common/partials/timeout.jsx:29:13)
  at apply (./scripts/common/partials/timeout.jsx:16:12)
...
(9 additional frame(s) were not displayed)
```

**Comment by nellh** [comment]
#939 is one cause of this, it looks like proxies holding onto index.html even though it's served with `max-age=0` - that should be fixed with #940

There's two other issues I see leading to this:

1. Users navigating to private datasets they don't have access to. We saw 8 queries with this issue in the last 24 hours.
2. Some snapshots are still timing out resolving files. 5 queries in 24 hours.

**Comment by chrisgorgo** [comment]
I still see quite a few of those issues. Mostly when accessing https://openneuro.org/dashboard/datasets

**Comment by nellh** [comment]
This was removed as part of #911. The timeout is no longer used, if a request error occurs we show as much as we can and report it to Sentry.
